# Generated by Django 4.0.3 on 2022-03-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_manager', models.CharField(max_length=20)),
                ('time_date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
    ]
