# Generated by Django 4.0.3 on 2022-04-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(max_length=200)),
                ('_composer', models.CharField(max_length=100)),
                ('_conductor', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='timeinfo',
            options={'ordering': ['_time_date', '_time_start'], 'verbose_name': '타임 정보', 'verbose_name_plural': '타임 정보'},
        ),
        migrations.RenameField(
            model_name='timeinfo',
            old_name='time_date',
            new_name='_time_date',
        ),
        migrations.RenameField(
            model_name='timeinfo',
            old_name='time_end',
            new_name='_time_end',
        ),
        migrations.RenameField(
            model_name='timeinfo',
            old_name='time_start',
            new_name='_time_start',
        ),
        migrations.RemoveField(
            model_name='timeinfo',
            name='time_manager',
        ),
        migrations.AddField(
            model_name='timeinfo',
            name='_time_manager',
            field=models.CharField(default='타임 담당자', help_text='타임 담당자 이름', max_length=100),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_player', models.CharField(max_length=100)),
                ('_music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_manage.music')),
            ],
        ),
        migrations.AddField(
            model_name='music',
            name='_timeinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_manage.timeinfo'),
        ),
    ]
