# Generated by Django 4.0.3 on 2022-04-10 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_manage', '0003_rename__timeinfo_music__time_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinfo',
            name='_time_unique_id',
        ),
    ]
