# Generated by Django 4.0.3 on 2022-04-10 03:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('time_manage', '0004_remove_timeinfo__time_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeinfo',
            name='_time_unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
