# Generated by Django 4.0.3 on 2022-04-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_manage', '0005_timeinfo__time_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='_orchestra',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
