# Generated by Django 4.0.3 on 2022-04-11 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_manage', '0006_music__orchestra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeinfo',
            old_name='_time_unique_id',
            new_name='time_unique_id',
        ),
    ]
