# Generated by Django 4.0.3 on 2022-04-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_manage', '0009_alter_timeinfo_options_alter_music_music_conductor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_label_id',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='music',
            name='music_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='music_source',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
