# Generated by Django 4.0.3 on 2022-05-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_manage', '0015_alter_music_music_conductor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['id', 'player_name'], 'verbose_name': '연주자', 'verbose_name_plural': '연주자'},
        ),
        migrations.AddField(
            model_name='player',
            name='player_instrument',
            field=models.CharField(blank=True, default='악기', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(default='연주자이름', max_length=100),
        ),
    ]
