# Generated by Django 4.0.4 on 2022-08-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_manage', '0017_timeinfo_time_manager_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinfo',
            name='time_manager',
            field=models.CharField(max_length=100),
        ),
    ]
