# Generated by Django 4.2 on 2023-06-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_manage', '0019_alter_timeinfo_time_manager_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeinfo',
            name='time_comment_etc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='timeinfo',
            name='time_comment_gigi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='timeinfo',
            name='time_comment_music',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_source',
            field=models.CharField(default='ROON', max_length=100),
        ),
    ]
